# This file is a general .xdc for the Zybo Z7 Rev. B
# It is compatible with the Zybo Z7-20 and Zybo Z7-10
# To use it in a project:
# - uncomment the lines corresponding to used pins
# - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

#Clock signal
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk_i]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk_i]

#Switches
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {port_b[53]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {port_b[54]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {port_b[55]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {port_b[56]}]


#Buttons
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {port_b[57]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {port_b[58]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports {port_b[59]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {port_b[60]}]
#set_property -dict { PACKAGE_PIN B13   IOSTANDARD LVCMOS33 } [get_ports { test }]; #IO_L7P_T1_34 Sch=btn[4]
#set_property -dict { PACKAGE_PIN B9   IOSTANDARD LVCMOS33 } [get_ports { test }]; #IO_L7P_T1_34 Sch=btn[5]

#LEDs
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {port_b[61]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {port_b[62]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {port_b[63]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {port_b[64]}]
#set_property -dict { PACKAGE_PIN D8   IOSTANDARD LVCMOS33 } [get_ports { test }]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]

##RGB LED 5 (Zybo Z7-20 only)
#set_property -dict { PACKAGE_PIN Y11   IOSTANDARD LVCMOS33 } [get_ports { led5_r }]; #IO_L18N_T2_13 Sch=led5_r
#set_property -dict { PACKAGE_PIN T5    IOSTANDARD LVCMOS33 } [get_ports { led5_g }]; #IO_L19P_T3_13 Sch=led5_g
#set_property -dict { PACKAGE_PIN Y12   IOSTANDARD LVCMOS33 } [get_ports { led5_b }]; #IO_L20P_T3_13 Sch=led5_b

#RGB LED 6
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {port_b[65]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {port_b[66]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {port_b[67]}]


#Audio Codec
# Clock for 48 kHz sampling rate
create_clock -period 81.380 -waveform {0.000 40.690} [get_ports {port_b[1]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports {port_b[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {port_b[1]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {port_b[2]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {port_b[3]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {port_b[4]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {port_b[5]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {port_b[6]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {port_b[7]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {port_b[8]}]


#Additional Ethernet signals
set_property PACKAGE_PIN F16 [get_ports {port_b[68]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b[68]}]
set_property PULLUP true [get_ports {port_b[68]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {port_b[69]}]


#USB-OTG over-current detect pin
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {port_b[70]}]


##Fan (Zybo Z7-20 only)
#set_property -dict { PACKAGE_PIN Y13   IOSTANDARD LVCMOS33  PULLUP true    } [get_ports { fan_fb_pu }]; #IO_L20N_T3_13 Sch=fan_fb_pu

#HDMI Clock
#create_clock -period 0.6734 -waveform {0.000 0.3367} [get_ports {port_b[45]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {port_b[45]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets port_b_IBUF__0[50]] 
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets io_instance/design_1_i/IO_0/U0/hdmi_vde]


#HDMI RX
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {port_b[46]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {port_b[47]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {port_b[48]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD TMDS_33} [get_ports {port_i[0]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD TMDS_33} [get_ports {port_i[1]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD TMDS_33} [get_ports {port_i[2]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD TMDS_33} [get_ports {port_i[3]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD TMDS_33} [get_ports {port_i[4]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD TMDS_33} [get_ports {port_i[5]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD TMDS_33} [get_ports {port_i[6]}]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD TMDS_33} [get_ports {port_i[7]}]

##HDMI RX CEC (Zybo Z7-20 only)
#set_property -dict { PACKAGE_PIN Y8    IOSTANDARD LVCMOS33 } [get_ports { hdmi_rx_cec }]; #IO_L14N_T2_SRCC_13 Sch=hdmi_rx_cec


#HDMI TX
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {port_b[49]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {port_b[50]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {port_b[51]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD TMDS_33} [get_ports {port_o[0]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD TMDS_33} [get_ports {port_o[1]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD TMDS_33} [get_ports {port_o[2]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD TMDS_33} [get_ports {port_o[3]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD TMDS_33} [get_ports {port_o[4]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD TMDS_33} [get_ports {port_o[5]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD TMDS_33} [get_ports {port_o[6]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD TMDS_33} [get_ports {port_o[7]}]

#HDMI TX CEC
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {port_b[52]}]


#Pmod Header JA (XADC)
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {port_b[9]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {port_b[10]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {port_b[11]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {port_b[12]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {port_b[13]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {port_b[14]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {port_b[15]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {port_b[16]}]


##Pmod Header JB (Zybo Z7-20 only)
#set_property -dict { PACKAGE_PIN V8    IOSTANDARD LVCMOS33     } [get_ports { port_b[17] }]; #IO_L15P_T2_DQS_13 Sch=jb_p[1]
#set_property -dict { PACKAGE_PIN W8    IOSTANDARD LVCMOS33     } [get_ports { port_b[18] }]; #IO_L15N_T2_DQS_13 Sch=jb_n[1]
#set_property -dict { PACKAGE_PIN U7    IOSTANDARD LVCMOS33     } [get_ports { port_b[19] }]; #IO_L11P_T1_SRCC_13 Sch=jb_p[2]
#set_property -dict { PACKAGE_PIN V7    IOSTANDARD LVCMOS33     } [get_ports { port_b[20] }]; #IO_L11N_T1_SRCC_13 Sch=jb_n[2]
#set_property -dict { PACKAGE_PIN Y7    IOSTANDARD LVCMOS33     } [get_ports { port_b[21] }]; #IO_L13P_T2_MRCC_13 Sch=jb_p[3]
#set_property -dict { PACKAGE_PIN Y6    IOSTANDARD LVCMOS33     } [get_ports { port_b[22] }]; #IO_L13N_T2_MRCC_13 Sch=jb_n[3]
#set_property -dict { PACKAGE_PIN V6    IOSTANDARD LVCMOS33     } [get_ports { port_b[23] }]; #IO_L22P_T3_13 Sch=jb_p[4]
#set_property -dict { PACKAGE_PIN W6    IOSTANDARD LVCMOS33     } [get_ports { port_b[24] }]; #IO_L22N_T3_13 Sch=jb_n[4]


#Pmod Header JC
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {port_b[17]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports {port_b[18]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {port_b[19]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {port_b[20]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {port_b[21]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {port_b[22]}]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports {port_b[23]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {port_b[24]}]


#Pmod Header JD
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {port_b[25]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {port_b[26]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {port_b[27]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {port_b[28]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {port_b[29]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {port_b[30]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {port_b[31]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {port_b[32]}]


#Pmod Header JE
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {port_b[33]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {port_b[34]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {port_b[35]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {port_b[36]}]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {port_b[37]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {port_b[38]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {port_b[39]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {port_b[40]}]


#Pcam MIPI CSI-2 Connector
# This configuration expects the sensor to use 672Mbps/lane = 336 MHz HS_Clk
#create_clock -period 2.976 -waveform {0.000 1.488} [get_ports {port_b[71]}]
create_clock -period 2.976 -waveform {0.000 1.488} [get_ports {port_i[15]}]
set_property INTERNAL_VREF 0.6 [get_iobanks 35]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD HSUL_12} [get_ports {port_i[8]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD HSUL_12} [get_ports {port_i[9]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD HSUL_12} [get_ports {port_i[10]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD HSUL_12} [get_ports {port_i[11]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD HSUL_12} [get_ports {port_i[12]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD HSUL_12} [get_ports {port_i[13]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVDS_25} [get_ports {port_i[14]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVDS_25} [get_ports {port_i[15]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVDS_25} [get_ports {port_i[16]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVDS_25} [get_ports {port_i[17]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVDS_25} [get_ports {port_i[18]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVDS_25} [get_ports {port_i[19]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {port_b[41]}]
set_property PACKAGE_PIN G20 [get_ports {port_b[42]}]
set_property IOSTANDARD LVCMOS33 [get_ports {port_b[42]}]
set_property PULLUP true [get_ports {port_b[42]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {port_b[43]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {port_b[44]}]


#Unloaded Crypto Chip SWI (for future use)
#set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {port_b[45]}]


##Unconnected Pins (Zybo Z7-20 only)
#set_property PACKAGE_PIN T9 [get_ports {netic19_t9}]; #IO_L12P_T1_MRCC_13
#set_property PACKAGE_PIN U10 [get_ports {netic19_u10}]; #IO_L12N_T1_MRCC_13
#set_property PACKAGE_PIN U5 [get_ports {netic19_u5}]; #IO_L19N_T3_VREF_13
#set_property PACKAGE_PIN U8 [get_ports {netic19_u8}]; #IO_L17N_T2_13
#set_property PACKAGE_PIN U9 [get_ports {netic19_u9}]; #IO_L17P_T2_13
#set_property PACKAGE_PIN V10 [get_ports {netic19_v10}]; #IO_L21N_T3_DQS_13
#set_property PACKAGE_PIN V11 [get_ports {netic19_v11}]; #IO_L21P_T3_DQS_13
#set_property PACKAGE_PIN V5 [get_ports {netic19_v5}]; #IO_L6N_T0_VREF_13
#set_property PACKAGE_PIN W10 [get_ports {netic19_w10}]; #IO_L16P_T2_13
#set_property PACKAGE_PIN W11 [get_ports {netic19_w11}]; #IO_L18P_T2_13
#set_property PACKAGE_PIN W9 [get_ports {netic19_w9}]; #IO_L16N_T2_13
#set_property PACKAGE_PIN Y9 [get_ports {netic19_y9}]; #IO_L14P_T2_SRCC_13



#  GPIO / gpio[53] / MIO[53]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[53]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[53]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[53]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[53]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[53]}]
#  GPIO / gpio[52] / MIO[52]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[52]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[52]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[52]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[52]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[52]}]
#  USB 1 / data[7] / MIO[51]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[51]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[51]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[51]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[51]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[51]}]
#  USB 1 / data[6] / MIO[50]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[50]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[50]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[50]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[50]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[50]}]
#  USB 1 / data[5] / MIO[49]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[49]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[49]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[49]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[49]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[49]}]
#  USB 1 / clk / MIO[48]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[48]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[48]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[48]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[48]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[48]}]
#  USB 1 / data[3] / MIO[47]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[47]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[47]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[47]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[47]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[47]}]
#  USB 1 / data[2] / MIO[46]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[46]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[46]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[46]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[46]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[46]}]
#  USB 1 / data[1] / MIO[45]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[45]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[45]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[45]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[45]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[45]}]
#  USB 1 / data[0] / MIO[44]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[44]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[44]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[44]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[44]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[44]}]
#  USB 1 / nxt / MIO[43]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[43]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[43]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[43]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[43]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[43]}]
#  USB 1 / stp / MIO[42]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[42]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[42]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[42]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[42]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[42]}]
#  USB 1 / dir / MIO[41]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[41]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[41]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[41]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[41]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[41]}]
#  USB 1 / data[4] / MIO[40]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[40]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[40]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[40]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[40]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[40]}]
#  USB 0 / data[7] / MIO[39]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[39]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[39]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[39]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[39]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[39]}]
#  USB 0 / data[6] / MIO[38]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[38]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[38]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[38]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[38]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[38]}]
#  USB 0 / data[5] / MIO[37]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[37]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[37]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[37]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[37]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[37]}]
#  USB 0 / clk / MIO[36]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[36]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[36]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[36]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[36]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[36]}]
#  USB 0 / data[3] / MIO[35]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[35]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[35]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[35]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[35]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[35]}]
#  USB 0 / data[2] / MIO[34]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[34]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[34]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[34]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[34]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[34]}]
#  USB 0 / data[1] / MIO[33]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[33]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[33]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[33]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[33]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[33]}]
#  USB 0 / data[0] / MIO[32]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[32]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[32]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[32]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[32]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[32]}]
#  USB 0 / nxt / MIO[31]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[31]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[31]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[31]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[31]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[31]}]
#  USB 0 / stp / MIO[30]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[30]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[30]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[30]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[30]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[30]}]
#  USB 0 / dir / MIO[29]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[29]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[29]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[29]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[29]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[29]}]
#  USB 0 / data[4] / MIO[28]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[28]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[28]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[28]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[28]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[28]}]
#  I2C Reset / reset / MIO[27]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[27]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[27]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[27]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[27]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[27]}]
#  USB Reset / reset / MIO[26]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[26]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[26]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[26]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[26]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[26]}]
#  ENET Reset / reset / MIO[25]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[25]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[25]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[25]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[25]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[25]}]
#  GPIO / gpio[24] / MIO[24]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[24]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[24]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[24]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[24]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[24]}]
#  GPIO / gpio[23] / MIO[23]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[23]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[23]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[23]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[23]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[23]}]
#  GPIO / gpio[22] / MIO[22]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[22]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[22]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[22]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[22]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[22]}]
#  GPIO / gpio[21] / MIO[21]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[21]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[21]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[21]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[21]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[21]}]
#  GPIO / gpio[20] / MIO[20]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[20]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[20]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[20]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[20]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[20]}]
#  GPIO / gpio[19] / MIO[19]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[19]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[19]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[19]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[19]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[19]}]
#  GPIO / gpio[18] / MIO[18]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[18]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[18]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[18]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[18]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[18]}]
#  GPIO / gpio[17] / MIO[17]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[17]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[17]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[17]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[17]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[17]}]
#  GPIO / gpio[16] / MIO[16]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[16]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[16]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[16]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[16]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[16]}]
#  GPIO / gpio[15] / MIO[15]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[15]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[15]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[15]}]
#  GPIO / gpio[14] / MIO[14]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[14]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[14]}]
#  Quad SPI Flash / qspi1_io[3] / MIO[13]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[13]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[13]}]
#  Quad SPI Flash / qspi1_io[2] / MIO[12]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[12]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[12]}]
#  Quad SPI Flash / qspi1_io[1] / MIO[11]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[11]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[11]}]
#  Quad SPI Flash / qspi1_io[0] / MIO[10]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[10]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[10]}]
#  Quad SPI Flash / qspi1_sclk / MIO[9]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[9]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[9]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[9]}]
#  Quad SPI Flash / qspi_fbclk / MIO[8]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[8]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[8]}]
#  GPIO / gpio[7] / MIO[7]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[7]}]
#  Quad SPI Flash / qspi0_sclk / MIO[6]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[6]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[6]}]
#  Quad SPI Flash / qspi0_io[3]/HOLD_B / MIO[5]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[5]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[5]}]
#  Quad SPI Flash / qspi0_io[2] / MIO[4]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[4]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[4]}]
#  Quad SPI Flash / qspi0_io[1] / MIO[3]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[3]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[3]}]
#  Quad SPI Flash / qspi0_io[0] / MIO[2]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[2]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[2]}]
#  Quad SPI Flash / qspi0_ss_b / MIO[1]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[1]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[1]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[1]}]
#  Quad SPI Flash / qspi1_ss_b / MIO[0]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[0]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property IOSTANDARD SSTL15 [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_ras_n]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_odt]
set_property SLEW SLOW [get_ports DDR_odt]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property IOSTANDARD SSTL15 [get_ports DDR_reset_n]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[9]}]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[8]}]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[7]}]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[6]}]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[5]}]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[4]}]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[3]}]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[31]}]
set_property SLEW FAST [get_ports {DDR_dq[31]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[31]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[30]}]
set_property SLEW FAST [get_ports {DDR_dq[30]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[30]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[2]}]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[29]}]
set_property SLEW FAST [get_ports {DDR_dq[29]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[29]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[28]}]
set_property SLEW FAST [get_ports {DDR_dq[28]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[28]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[27]}]
set_property SLEW FAST [get_ports {DDR_dq[27]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[27]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[26]}]
set_property SLEW FAST [get_ports {DDR_dq[26]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[26]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[25]}]
set_property SLEW FAST [get_ports {DDR_dq[25]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[25]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[24]}]
set_property SLEW FAST [get_ports {DDR_dq[24]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[24]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[23]}]
set_property SLEW FAST [get_ports {DDR_dq[23]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[23]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[22]}]
set_property SLEW FAST [get_ports {DDR_dq[22]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[22]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[21]}]
set_property SLEW FAST [get_ports {DDR_dq[21]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[21]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[20]}]
set_property SLEW FAST [get_ports {DDR_dq[20]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[20]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[1]}]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[19]}]
set_property SLEW FAST [get_ports {DDR_dq[19]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[19]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[18]}]
set_property SLEW FAST [get_ports {DDR_dq[18]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[18]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[17]}]
set_property SLEW FAST [get_ports {DDR_dq[17]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[17]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[16]}]
set_property SLEW FAST [get_ports {DDR_dq[16]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[16]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[15]}]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[14]}]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[13]}]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[12]}]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[11]}]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[10]}]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[0]}]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[3]}]
set_property SLEW FAST [get_ports {DDR_dm[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[2]}]
set_property SLEW FAST [get_ports {DDR_dm[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[1]}]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[0]}]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports DDR_cs_n]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cke]
set_property SLEW SLOW [get_ports DDR_cke]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_p]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_n]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cas_n]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[2]}]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[1]}]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[0]}]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[9]}]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[8]}]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[7]}]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[6]}]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[5]}]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[4]}]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[3]}]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[2]}]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[1]}]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[14]}]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[13]}]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[12]}]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[11]}]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[10]}]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[0]}]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_srstb]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN B10 [get_ports FIXED_IO_ps_srstb]
set_property PACKAGE_PIN P4 [get_ports DDR_ras_n]
set_property PACKAGE_PIN C7 [get_ports FIXED_IO_ps_porb]
set_property PACKAGE_PIN N5 [get_ports DDR_odt]
set_property PACKAGE_PIN C11 [get_ports {FIXED_IO_mio[53]}]
set_property PACKAGE_PIN C10 [get_ports {FIXED_IO_mio[52]}]
set_property PACKAGE_PIN B9 [get_ports {FIXED_IO_mio[51]}]
set_property PACKAGE_PIN B13 [get_ports {FIXED_IO_mio[50]}]
set_property PACKAGE_PIN C12 [get_ports {FIXED_IO_mio[49]}]
set_property PACKAGE_PIN B12 [get_ports {FIXED_IO_mio[48]}]
set_property PACKAGE_PIN B14 [get_ports {FIXED_IO_mio[47]}]
set_property PACKAGE_PIN D16 [get_ports {FIXED_IO_mio[46]}]
set_property PACKAGE_PIN B15 [get_ports {FIXED_IO_mio[45]}]
set_property PACKAGE_PIN F13 [get_ports {FIXED_IO_mio[44]}]
set_property PACKAGE_PIN A9 [get_ports {FIXED_IO_mio[43]}]
set_property PACKAGE_PIN E12 [get_ports {FIXED_IO_mio[42]}]
set_property PACKAGE_PIN C17 [get_ports {FIXED_IO_mio[41]}]
set_property PACKAGE_PIN D14 [get_ports {FIXED_IO_mio[40]}]
set_property PACKAGE_PIN C18 [get_ports {FIXED_IO_mio[39]}]
set_property PACKAGE_PIN E13 [get_ports {FIXED_IO_mio[38]}]
set_property PACKAGE_PIN A10 [get_ports {FIXED_IO_mio[37]}]
set_property PACKAGE_PIN A11 [get_ports {FIXED_IO_mio[36]}]
set_property PACKAGE_PIN F12 [get_ports {FIXED_IO_mio[35]}]
set_property PACKAGE_PIN A12 [get_ports {FIXED_IO_mio[34]}]
set_property PACKAGE_PIN D15 [get_ports {FIXED_IO_mio[33]}]
set_property PACKAGE_PIN A14 [get_ports {FIXED_IO_mio[32]}]
set_property PACKAGE_PIN E16 [get_ports {FIXED_IO_mio[31]}]
set_property PACKAGE_PIN C15 [get_ports {FIXED_IO_mio[30]}]
set_property PACKAGE_PIN C13 [get_ports {FIXED_IO_mio[29]}]
set_property PACKAGE_PIN C16 [get_ports {FIXED_IO_mio[28]}]
set_property PACKAGE_PIN D13 [get_ports {FIXED_IO_mio[27]}]
set_property PACKAGE_PIN A15 [get_ports {FIXED_IO_mio[26]}]
set_property PACKAGE_PIN F15 [get_ports {FIXED_IO_mio[25]}]
set_property PACKAGE_PIN A16 [get_ports {FIXED_IO_mio[24]}]
set_property PACKAGE_PIN D11 [get_ports {FIXED_IO_mio[23]}]
set_property PACKAGE_PIN B17 [get_ports {FIXED_IO_mio[22]}]
set_property PACKAGE_PIN F14 [get_ports {FIXED_IO_mio[21]}]
set_property PACKAGE_PIN A17 [get_ports {FIXED_IO_mio[20]}]
set_property PACKAGE_PIN D10 [get_ports {FIXED_IO_mio[19]}]
set_property PACKAGE_PIN B18 [get_ports {FIXED_IO_mio[18]}]
set_property PACKAGE_PIN E14 [get_ports {FIXED_IO_mio[17]}]
set_property PACKAGE_PIN A19 [get_ports {FIXED_IO_mio[16]}]
set_property PACKAGE_PIN C8 [get_ports {FIXED_IO_mio[15]}]
set_property PACKAGE_PIN C5 [get_ports {FIXED_IO_mio[14]}]
set_property PACKAGE_PIN E8 [get_ports {FIXED_IO_mio[13]}]
set_property PACKAGE_PIN D9 [get_ports {FIXED_IO_mio[12]}]
set_property PACKAGE_PIN C6 [get_ports {FIXED_IO_mio[11]}]
set_property PACKAGE_PIN E9 [get_ports {FIXED_IO_mio[10]}]
set_property PACKAGE_PIN B5 [get_ports {FIXED_IO_mio[9]}]
set_property PACKAGE_PIN D5 [get_ports {FIXED_IO_mio[8]}]
set_property PACKAGE_PIN D8 [get_ports {FIXED_IO_mio[7]}]
set_property PACKAGE_PIN A5 [get_ports {FIXED_IO_mio[6]}]
set_property PACKAGE_PIN A6 [get_ports {FIXED_IO_mio[5]}]
set_property PACKAGE_PIN B7 [get_ports {FIXED_IO_mio[4]}]
set_property PACKAGE_PIN D6 [get_ports {FIXED_IO_mio[3]}]
set_property PACKAGE_PIN B8 [get_ports {FIXED_IO_mio[2]}]
set_property PACKAGE_PIN A7 [get_ports {FIXED_IO_mio[1]}]
set_property PACKAGE_PIN E6 [get_ports {FIXED_IO_mio[0]}]
set_property PACKAGE_PIN B4 [get_ports DDR_reset_n]
set_property PACKAGE_PIN W5 [get_ports {DDR_dqs_p[3]}]
set_property PACKAGE_PIN M5 [get_ports DDR_we_n]
set_property PACKAGE_PIN G5 [get_ports FIXED_IO_ddr_vrn]
set_property PACKAGE_PIN H5 [get_ports FIXED_IO_ddr_vrp]
set_property PACKAGE_PIN N2 [get_ports {DDR_addr[0]}]
set_property PACKAGE_PIN K2 [get_ports {DDR_addr[1]}]
set_property PACKAGE_PIN M3 [get_ports {DDR_addr[2]}]
set_property PACKAGE_PIN K3 [get_ports {DDR_addr[3]}]
set_property PACKAGE_PIN M4 [get_ports {DDR_addr[4]}]
set_property PACKAGE_PIN L1 [get_ports {DDR_addr[5]}]
set_property PACKAGE_PIN L4 [get_ports {DDR_addr[6]}]
set_property PACKAGE_PIN K4 [get_ports {DDR_addr[7]}]
set_property PACKAGE_PIN K1 [get_ports {DDR_addr[8]}]
set_property PACKAGE_PIN J4 [get_ports {DDR_addr[9]}]
set_property PACKAGE_PIN F5 [get_ports {DDR_addr[10]}]
set_property PACKAGE_PIN G4 [get_ports {DDR_addr[11]}]
set_property PACKAGE_PIN E4 [get_ports {DDR_addr[12]}]
set_property PACKAGE_PIN F4 [get_ports {DDR_addr[14]}]
set_property PACKAGE_PIN D4 [get_ports {DDR_addr[13]}]
set_property PACKAGE_PIN L5 [get_ports {DDR_ba[0]}]
set_property PACKAGE_PIN R4 [get_ports {DDR_ba[1]}]
set_property PACKAGE_PIN J5 [get_ports {DDR_ba[2]}]
set_property PACKAGE_PIN P5 [get_ports DDR_cas_n]
set_property PACKAGE_PIN N3 [get_ports DDR_cke]
set_property PACKAGE_PIN M2 [get_ports DDR_ck_n]
set_property PACKAGE_PIN L2 [get_ports DDR_ck_p]
set_property PACKAGE_PIN E7 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN N1 [get_ports DDR_cs_n]
set_property PACKAGE_PIN A1 [get_ports {DDR_dm[0]}]
set_property PACKAGE_PIN F1 [get_ports {DDR_dm[1]}]
set_property PACKAGE_PIN T1 [get_ports {DDR_dm[2]}]
set_property PACKAGE_PIN Y1 [get_ports {DDR_dm[3]}]
set_property PACKAGE_PIN C3 [get_ports {DDR_dq[0]}]
set_property PACKAGE_PIN B3 [get_ports {DDR_dq[1]}]
set_property PACKAGE_PIN A2 [get_ports {DDR_dq[2]}]
set_property PACKAGE_PIN A4 [get_ports {DDR_dq[3]}]
set_property PACKAGE_PIN D3 [get_ports {DDR_dq[4]}]
set_property PACKAGE_PIN D1 [get_ports {DDR_dq[5]}]
set_property PACKAGE_PIN C1 [get_ports {DDR_dq[6]}]
set_property PACKAGE_PIN E1 [get_ports {DDR_dq[7]}]
set_property PACKAGE_PIN E2 [get_ports {DDR_dq[8]}]
set_property PACKAGE_PIN E3 [get_ports {DDR_dq[9]}]
set_property PACKAGE_PIN G3 [get_ports {DDR_dq[10]}]
set_property PACKAGE_PIN H3 [get_ports {DDR_dq[11]}]
set_property PACKAGE_PIN J3 [get_ports {DDR_dq[12]}]
set_property PACKAGE_PIN H2 [get_ports {DDR_dq[13]}]
set_property PACKAGE_PIN H1 [get_ports {DDR_dq[14]}]
set_property PACKAGE_PIN J1 [get_ports {DDR_dq[15]}]
set_property PACKAGE_PIN P1 [get_ports {DDR_dq[16]}]
set_property PACKAGE_PIN P3 [get_ports {DDR_dq[17]}]
set_property PACKAGE_PIN R3 [get_ports {DDR_dq[18]}]
set_property PACKAGE_PIN R1 [get_ports {DDR_dq[19]}]
set_property PACKAGE_PIN T4 [get_ports {DDR_dq[20]}]
set_property PACKAGE_PIN U4 [get_ports {DDR_dq[21]}]
set_property PACKAGE_PIN U2 [get_ports {DDR_dq[22]}]
set_property PACKAGE_PIN U3 [get_ports {DDR_dq[23]}]
set_property PACKAGE_PIN V1 [get_ports {DDR_dq[24]}]
set_property PACKAGE_PIN Y3 [get_ports {DDR_dq[25]}]
set_property PACKAGE_PIN W1 [get_ports {DDR_dq[26]}]
set_property PACKAGE_PIN Y4 [get_ports {DDR_dq[27]}]
set_property PACKAGE_PIN Y2 [get_ports {DDR_dq[28]}]
set_property PACKAGE_PIN W3 [get_ports {DDR_dq[29]}]
set_property PACKAGE_PIN V2 [get_ports {DDR_dq[30]}]
set_property PACKAGE_PIN V3 [get_ports {DDR_dq[31]}]
set_property PACKAGE_PIN B2 [get_ports {DDR_dqs_n[0]}]
set_property PACKAGE_PIN F2 [get_ports {DDR_dqs_n[1]}]
set_property PACKAGE_PIN T2 [get_ports {DDR_dqs_n[2]}]
set_property PACKAGE_PIN W4 [get_ports {DDR_dqs_n[3]}]
set_property PACKAGE_PIN C2 [get_ports {DDR_dqs_p[0]}]
set_property PACKAGE_PIN G2 [get_ports {DDR_dqs_p[1]}]
set_property PACKAGE_PIN R2 [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]


